### PR TITLE
[Fix]: ScrollIntoView on terminal children update

### LINKED ISSUE #33: Why is scrollIntoViewRef used onload?
I'm loading multiple terminals in one page and my page jumps down to the last terminal on inital load.
I read the source code and find that this behavior is done on purpose by scrollIntoViewRef. Why is this the case? Can you just remove it?

### PR DESCRIPTION
**Pull request by romulorod**
Everytime the children was updated this was scrolling back into view, and it only does so at the end of the key down input command, after the user presses Enter.

Fixes #33

### CODE REVIEW

**Comment by romulorod** [comment]
I'm trying to use this lib in my project but without the onInput prop, I'm changing the terminal children to render a list of items that gets updated every 3m based on the API response, but when I update the children, the focus get restored and I think we could improve it by restoring the focus on keydown event after the user press Enter.

**Review by jonmbake — APPROVED** [review]

File: src/index.tsx [hunk 1]
```diff
@@ -61,6 +61,7 @@ const Terminal = ({name, prompt, height = "600px", colorMode, onInput, children,
       onInput(currentLineInput);
       setCursorPos(0);
       setCurrentLineInput('');
+      scrollIntoViewRef?.current?.scrollIntoView({ behavior: "auto", block: "center" });
```
Comment (jonmbake) [inline src/index.tsx:64]: Merged this, but did a little additional testing (in Firefox) after merge. This doesn't seem to be working quite right:
- Entire terminal now moves down on first Enter; the terminal should not change positions
- When reaching the bottom, the cursor now is hidden slightly
Is there a reason you decided to change it from `block: nearest` to `block: center`?

Comment (romulorod) [reply src/index.tsx:64]: Hey Jon, hope you're doing great!
I changed from nearest to center because it also fixed some scrollIntoView bugs, I have some loom videos to show if you'd like to see... I'll attach it

[using-nearest.webm](https://github.com/jonmbake/react-terminal-ui/assets/80011318/ce13cfca-a159-42ae-a9b7-7469aaedc980)

[using-center.webm](https://github.com/jonmbake/react-terminal-ui/assets/80011318/f6340a59-e74d-4d40-bd4e-4a31e16fb2ea)

Comment (jonmbake) [reply src/index.tsx:64]: The ScrollIntoView is intended to get the cursor to scroll into view if the inputs go longer than the terminal height-- not to try to scroll back into view if the user manually scrolls up or down on the page.

This change introduces a new bug where the cursor is hidden when it reaches the bottom.
